### ISSUE TITLE
Cycling through elements with the same accesskey 

### ISSUE THREAD

**Issue by blabno** [denis-sokolov/jQuery-Accesskey#3]
Cycling through elements within UI/LI is ok, but in case of i.e. two links next to each other this doesn't work.

```
`<a href="#richfaces" accesskey="r">RichFaces</a> compomponent development with
<a href="#jrebel" accesskey="r">jRebel</a> is way fast.`
```

**Comment by denis-sokolov** [comment]
This works for me. :(
Could you try it again with a new version?
